
#The name of your workflow.
name:  Test, build and deploy Flutter app
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: macos-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      - run: flutter pub get
      # run static analys code
      - run: flutter  analyze
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
  build_deploy:
    #if conditional to prevent a job from running
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: macos-latest
    #Identifies any jobs that must complete successfully before this job will run. 
    needs: [test]
    name: Build  apk  and web
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      #enable macos,windows   and  web
      - run: flutter  config --enable-web
      #- run: flutter  config --enable-macos-desktop
      #- run: flutter  config --enable-windows-desktop
      - run: flutter pub get
      # build Android version
      - run: flutter build apk --debug --split-per-abi
      # This action will create a github release and optionally upload an artifact to it.
      # https://github.com/ncipollo/release-action
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app"
          token: ${{ secrets.GITHUB_TOKEN }}
      # build Flutter web version
      #- run: flutter build web
      # Handle the deploy process of your project to GitHub Pages.
      # https://github.com/JamesIves/github-pages-deploy-action
     # - uses: JamesIves/github-pages-deploy-action@releases/v3
      #  with:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        #  BASE_BRANCH: master
         # BRANCH: gh-pages
          #FOLDER: build/web